services:
  - type: web
    name: Datasmithing
    runtime: static
    staticPublishPath: ./output
    buildCommand: |
      pip install pelican Markdown & \
      python -m pelican content --output output --settings publishconf.py
